#!/usr/local/bin/php
<?php
/**
 * Generate /usr/local/etc/keepalived-bsd.conf (VRRPv3 [vrrp_instance] format)
 * from OPNsense config.xml. Called by configd (root) via keepalived.reconfigure.
 */

const CONF_FILE  = '/usr/local/etc/keepalived-bsd.conf';
const CONFIG_XML = '/conf/config.xml';

$xmlCfg = simplexml_load_file(CONFIG_XML);
if ($xmlCfg === false) {
    fwrite(STDERR, "keepalived-bsd reconfigure: cannot read " . CONFIG_XML . "\n");
    exit(1);
}

$ka = $xmlCfg->OPNsense->keepalived ?? null;
$g  = $ka ? ($ka->general ?? null) : null;

/* Map an OPNsense interface key (lan/opt1/…) to its real FreeBSD device
 * (igb0, igb0.10, …). Falls back to the key itself if unmapped. */
function bsd_ifname(string $key, SimpleXMLElement $ifaces): string
{
    $key = trim($key);
    if ($key === '') {
        return '';
    }
    $if = trim((string)($ifaces->$key->if ?? ''));
    return $if !== '' ? $if : $key;
}

// [global] — fallback priority + default DHCP backend for instances that omit them.
$out  = "# Generated by keepalived-bsd OPNsense plugin — do not edit manually\n";
$out .= "[global]\n";
$out .= 'priority = ' . trim((string)($g->priority ?? '100')) . "\n";
$defBackend = trim((string)($g->dhcp_backend ?? ''));
if ($defBackend !== '' && $defBackend !== 'none') {
    $out .= "dhcp_backend = {$defBackend}\n";
}
$out .= "\n";

// [vrrp_instance NAME] — SimpleXML iterates correctly for 0, 1, or N children.
foreach ($ka ? ($ka->vrrp_instances->vrrp_instance ?? []) : [] as $inst) {
    $name = trim((string)($inst->name ?? ''));
    if ($name === '') {
        continue;
    }
    $bsd = bsd_ifname((string)($inst->interface ?? ''), $xmlCfg->interfaces);

    $out .= "[vrrp_instance {$name}]\n";
    $out .= 'state             = ' . (trim((string)($inst->state ?? 'BACKUP')) ?: 'BACKUP') . "\n";
    $out .= "interface         = {$bsd}\n";
    $out .= 'unicast_src_ip    = ' . trim((string)($inst->unicast_src_ip ?? '')) . "\n";
    $out .= 'unicast_peer      = ' . trim((string)($inst->unicast_peer ?? '')) . "\n";
    $out .= 'virtual_router_id = ' . trim((string)($inst->virtual_router_id ?? '')) . "\n";
    $out .= 'priority          = ' . trim((string)($inst->priority ?? '100')) . "\n";
    $out .= 'advert_int        = ' . trim((string)($inst->advert_int ?? '5')) . "\n";
    $out .= 'preempt           = ' . (trim((string)($inst->preempt ?? '1')) === '1' ? 'yes' : 'no') . "\n";

    $backend = trim((string)($inst->dhcp_backend ?? ''));
    if ($backend !== '' && $backend !== 'none') {
        $out .= "dhcp_backend      = {$backend}\n";
    }
    $alias = trim((string)($inst->alias ?? ''));
    if ($alias !== '') {
        $out .= "alias             = {$alias}\n";
    }

    // VIP list: one per line (also accept comma-separated). Verbatim tokens
    // (ADDR/prefix [dev IF] [label L]) — the daemon parses/validates each.
    foreach (preg_split('/[\r\n,]+/', (string)($inst->vip ?? '')) as $vip) {
        $vip = trim($vip);
        if ($vip !== '') {
            $out .= "vip               = {$vip}\n";
        }
    }
    $out .= "\n";
}

// Write atomically: a partial config file could leave the daemon unstartable.
$tmp = CONF_FILE . '.tmp';
if (file_put_contents($tmp, $out) === false) {
    fwrite(STDERR, "keepalived-bsd reconfigure: cannot write " . $tmp . "\n");
    exit(1);
}
chmod($tmp, 0640);
if (!rename($tmp, CONF_FILE)) {
    fwrite(STDERR, "keepalived-bsd reconfigure: cannot replace " . CONF_FILE . "\n");
    @unlink($tmp);
    exit(1);
}

// Restart daemon if enabled; exit with daemon's exit code so configd reports errors.
if (trim((string)($g->enabled ?? '0')) === '1') {
    passthru('/usr/local/etc/rc.d/keepalived_bsd onerestart', $rc);
    exit($rc);
}

echo 'Configuration written to ' . CONF_FILE . "\n";
exit(0);
