#!/usr/local/bin/php
<?php
/**
 * Generate /usr/local/etc/keepalived-bsd.conf from OPNsense config.xml data.
 * Called by configd (root) via the keepalived.reconfigure action.
 */

const CONF_FILE  = '/usr/local/etc/keepalived-bsd.conf';
const CONFIG_XML = '/conf/config.xml';

$xmlCfg = simplexml_load_file(CONFIG_XML);
if ($xmlCfg === false) {
    fwrite(STDERR, "keepalived-bsd reconfigure: cannot read " . CONFIG_XML . "\n");
    exit(1);
}

$ka = $xmlCfg->OPNsense->keepalived ?? null;
$g  = $ka ? ($ka->general ?? null) : null;

function bsd_ifname(string $key, SimpleXMLElement $ifaces): string
{
    $if = trim((string)($ifaces->$key->if ?? ''));
    return $if !== '' ? $if : $key;
}

// [global]
$out  = "# Generated by keepalived-bsd OPNsense plugin — do not edit manually\n";
$out .= "[global]\n";
$out .= 'peer      = ' . trim((string)($g->peer      ?? '')) . "\n";
$out .= 'port      = ' . trim((string)($g->port      ?? '5405')) . "\n";
$out .= 'priority  = ' . trim((string)($g->priority  ?? '100')) . "\n";
$out .= 'heartbeat = ' . trim((string)($g->heartbeat ?? '1')) . "\n";
$out .= 'timeout   = ' . trim((string)($g->timeout   ?? '3')) . "\n";
$out .= 'preempt   = ' . (trim((string)($g->preempt ?? '1')) === '1' ? 'yes' : 'no') . "\n";
$out .= "\n";

// [iface …] — SimpleXML iterates correctly for 0, 1, or N children
foreach ($ka ? ($ka->interfaces->interface ?? []) : [] as $iface) {
    $ifaceKey = trim((string)($iface->iface ?? ''));
    if ($ifaceKey === '') {
        continue;
    }
    $bsd = bsd_ifname($ifaceKey, $xmlCfg->interfaces);
    $out .= "[iface {$bsd}]\n";
    $out .= 'vip = ' . trim((string)($iface->vip ?? '')) . "\n";
    $alias = trim((string)($iface->alias ?? ''));
    if ($alias !== '') {
        $out .= "alias = {$alias}\n";
    }
    $backend = trim((string)($iface->dhcp_backend ?? ''));
    // 'global' was the legacy "inherit from global" value — omit it so the
    // daemon uses its built-in ISC default.
    if ($backend !== '' && $backend !== 'global') {
        $out .= "dhcp_backend = {$backend}\n";
    }
    $out .= "\n";
}

// Write atomically: a partial config file could leave the daemon unstartable.
$tmp = CONF_FILE . '.tmp';
if (file_put_contents($tmp, $out) === false) {
    fwrite(STDERR, "keepalived-bsd reconfigure: cannot write " . $tmp . "\n");
    exit(1);
}
chmod($tmp, 0640);
if (!rename($tmp, CONF_FILE)) {
    fwrite(STDERR, "keepalived-bsd reconfigure: cannot replace " . CONF_FILE . "\n");
    @unlink($tmp);
    exit(1);
}

// Restart daemon if enabled; exit with daemon's exit code so configd reports errors.
if (trim((string)($g->enabled ?? '0')) === '1') {
    passthru('/usr/local/etc/rc.d/keepalived_bsd onerestart', $rc);
    exit($rc);
}

echo 'Configuration written to ' . CONF_FILE . "\n";
exit(0);
