#!/usr/local/bin/php
<?php
/**
 * Generate /usr/local/etc/keepalived-bsd.conf from OPNsense config.xml data.
 * Called by configd (root) via the keepalived.reconfigure action.
 */

require_once('config.inc');

global $config;

const CONF_FILE = '/usr/local/etc/keepalived-bsd.conf';

$ka = $config['OPNsense']['keepalived'] ?? [];
$g  = $ka['general'] ?? [];

function bsd_ifname(string $key): string
{
    global $config;
    return !empty($config['interfaces'][$key]['if'])
        ? $config['interfaces'][$key]['if']
        : $key;
}

// [global]
$out  = "# Generated by keepalived-bsd OPNsense plugin — do not edit manually\n";
$out .= "[global]\n";
$out .= 'peer      = ' . trim($g['peer']      ?? '') . "\n";
$out .= 'port      = ' . trim($g['port']      ?? '5405') . "\n";
$out .= 'priority  = ' . trim($g['priority']  ?? '100') . "\n";
$out .= 'heartbeat = ' . trim($g['heartbeat'] ?? '1') . "\n";
$out .= 'timeout   = ' . trim($g['timeout']   ?? '3') . "\n";
$out .= 'preempt   = ' . (($g['preempt'] ?? '1') === '1' ? 'yes' : 'no') . "\n";
$out .= "\n";

// [iface …] — ArrayField: single entry = assoc array, multiple = indexed array
$ifaces = $ka['interfaces']['interface'] ?? [];
if (!empty($ifaces) && isset($ifaces['iface'])) {
    $ifaces = [$ifaces]; // normalise single entry to list
}

foreach ($ifaces as $iface) {
    if (empty($iface['iface'])) {
        continue;
    }
    $bsd = bsd_ifname($iface['iface']);
    $out .= "[iface {$bsd}]\n";
    $out .= 'vip = ' . trim($iface['vip'] ?? '') . "\n";
    $alias = trim($iface['alias'] ?? '');
    if ($alias !== '') {
        $out .= "alias = {$alias}\n";
    }
    $backend = trim($iface['dhcp_backend'] ?? '');
    // 'global' was the legacy "inherit from global" value — omit it so the
    // daemon uses its built-in ISC default.
    if ($backend !== '' && $backend !== 'global') {
        $out .= "dhcp_backend = {$backend}\n";
    }
    $out .= "\n";
}

file_put_contents(CONF_FILE, $out);
chmod(CONF_FILE, 0640);

// Restart daemon if enabled; exit with daemon's exit code so configd reports errors.
if (($g['enabled'] ?? '0') === '1') {
    passthru('/usr/local/etc/rc.d/keepalived_bsd onerestart', $rc);
    exit($rc);
}

echo 'Configuration written to ' . CONF_FILE . "\n";
exit(0);
